"""Phase 40 — sandboxed patch+test execution boundary.

Phase 39's ``run_patched_test`` executes the patched module and the
hidden test in-process via ``exec`` against a fresh ``__main__``-
shaped dict. That is safe for the *self-authored* mini bank but
not for arbitrary patches generated by an external LLM against
arbitrary code: a malicious or merely buggy patch can ``import
os; os.system(...)`` straight into the bridge process.

Phase 40 adds a real execution boundary:

  * **``SubprocessSandbox``** — run the same compile+exec
    cycle inside a fresh ``python -c`` subprocess, with the
    patched source written to a tempdir, the test source
    importing it as a module, a wall-clock timeout, no stdin,
    and stdout/stderr captured. The subprocess inherits the
    bridge process's interpreter and site-packages; it does
    NOT inherit the bridge's open file descriptors, signal
    handlers, or process state. This is *isolation by
    process boundary*, not *isolation by capability*.

  * **``DockerSandbox``** — if a local Docker daemon is
    available, run the same cycle inside a short-lived
    container with ``--network=none``, ``--read-only``
    rootfs, a writable ``/work`` tmpfs, and a wall-clock
    timeout. The container image is configurable; the
    default (``python:3.11-slim``) is enough for the
    Phase-40 mini-bank smoke run. Docker is optional —
    ``DockerSandbox.is_available()`` returns False when
    no daemon is reachable, and the driver falls back to
    ``SubprocessSandbox``.

  * **``InProcessSandbox``** — wraps the existing Phase-39
    ``run_patched_test`` so the three backends share one
    ``Sandbox`` interface. Useful as a regression baseline
    and for the mini-bank precondition tests.

What is and is NOT isolated
---------------------------

| Property                              | InProcess | Subprocess | Docker  |
|---                                    |---        |---         |---      |
| Crash containment                     | no        | yes        | yes     |
| Wall-clock timeout                    | no        | yes        | yes     |
| Memory bound (heap)                   | no        | soft (rlimit) | yes (cgroup)  |
| Filesystem isolation                  | no        | tempdir-only | tmpfs read-only rootfs  |
| Network isolation                     | no        | no         | yes (--network=none)  |
| Capability/syscall isolation          | no        | no         | partial (default seccomp)  |
| Side-effect rollback on test failure  | no        | yes        | yes     |
| Untrusted-code safety                 | NO        | partial    | yes (modulo Docker CVEs)  |

The honest summary: **``SubprocessSandbox`` is the right
default for Phase 40**. It contains crashes, enforces wall-
clock and (best-effort) memory bounds, and isolates the
filesystem to a tempdir — which is enough to credibly run
the mini-bank against an LLM-generated patch without
trusting the patch. ``DockerSandbox`` is the right choice
for an external-corpus run; it is implemented but not
required for the Phase-40 mini-bank measurements.

What this module does NOT claim
-------------------------------

* ``SubprocessSandbox`` does NOT block arbitrary network
  egress. A patch that issues an outbound HTTPS request can
  still reach the network from the subprocess. The right
  remediation is the Docker backend.
* ``SubprocessSandbox`` does NOT prevent the patch from
  reading the host's filesystem outside the tempdir; only
  *writes* are sandboxed by the tempdir convention. Use
  Docker when read-side isolation matters.
* ``DockerSandbox`` inherits Docker's own threat model.
  Container escape via daemon CVEs is out of scope; this
  module is a research-grade boundary, not a production-
  grade sandbox.
* The substrate test grader (``run_patched_test``'s
  ``def test(module): ...`` contract) is unchanged. Tests
  that do not match this contract are the loader's problem,
  not the sandbox's.

Theoretical anchor: RESULTS_PHASE40.md § B.3 (Theorem
P40-3 — sandbox-boundary preservation: every Phase-39
oracle-ceiling result holds under every Phase-40 sandbox
backend; empirical equivalence on the mini bank).
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import textwrap
import time
from dataclasses import dataclass, field
from typing import Protocol

from .swe_bench_bridge import (
    APPLY_MODE_STRICT, SWEBenchStyleTask, WorkspaceResult,
    apply_patch, run_patched_test,
)


# =============================================================================
# Sandbox protocol
# =============================================================================


class Sandbox(Protocol):
    """Common interface for all execution backends.

    Implementations must:

      1. Apply ``patch`` to ``buggy_source`` (string substitutions).
      2. Compile the patched source.
      3. Load it as a module.
      4. Execute ``test_source`` against it; the test must
         define ``def test(module) -> None`` (the Phase-39
         contract).
      5. Return a ``WorkspaceResult`` whose ``error_kind`` is
         one of the canonical Phase-39 kinds, plus the new
         ``"timeout"`` and ``"sandbox_error"`` kinds.
    """

    def name(self) -> str: ...

    def run(self,
            *,
            buggy_source: str,
            patch: tuple[tuple[str, str], ...],
            test_source: str,
            module_name: str,
            timeout_s: float,
            apply_mode: str = APPLY_MODE_STRICT,
            ) -> WorkspaceResult: ...

    def is_available(self) -> bool: ...


# =============================================================================
# In-process sandbox (Phase 39 wrapped)
# =============================================================================


@dataclass
class InProcessSandbox:
    """Phase-39 in-process exec wrapped into the Phase-40 protocol.

    Provided so a driver can set ``--sandbox=in_process`` to
    reproduce Phase-39 numbers exactly (and to keep a fast
    regression baseline).
    """

    def name(self) -> str:
        return "in_process"

    def is_available(self) -> bool:
        return True

    def run(self,
            *,
            buggy_source: str,
            patch: tuple[tuple[str, str], ...],
            test_source: str,
            module_name: str,
            timeout_s: float = 30.0,
            apply_mode: str = APPLY_MODE_STRICT,
            ) -> WorkspaceResult:
        new_source, applied, reason = apply_patch(
            buggy_source, patch, mode=apply_mode)
        if not applied:
            return WorkspaceResult(
                patch_applied=False, syntax_ok=False,
                test_passed=False, error_kind="patch_no_match",
                error_detail=reason)
        # The Phase-39 in-process runner ignores ``timeout_s``
        # because there is no clean way to interrupt arbitrary
        # Python from a single thread. Honest reporting only.
        del timeout_s
        return run_patched_test(
            file_source=buggy_source, patched_source=new_source,
            test_source=test_source, module_name=module_name)


# =============================================================================
# Subprocess sandbox
# =============================================================================


_SUBPROCESS_RUNNER = textwrap.dedent('''
    """Subprocess-side runner — invoked by ``SubprocessSandbox``.

    Reads a JSON payload on stdin with keys ``patched_source`` /
    ``test_source`` / ``module_name``, executes them under the
    Phase-39 contract, prints a single JSON line on stdout, and
    exits 0. Any failure is captured and reported via the JSON
    payload, not via process exit code, so the parent can
    distinguish *test-level* failures from *sandbox-level*
    failures.
    """
    import io, json, sys, traceback
    from contextlib import redirect_stdout, redirect_stderr

    def _emit(payload):
        sys.__stdout__.write(json.dumps(payload) + "\\n")
        sys.__stdout__.flush()

    try:
        req = json.loads(sys.stdin.read())
    except Exception as ex:
        _emit({"ok": False, "kind": "sandbox_error",
               "detail": f"input parse failed: {type(ex).__name__}: {ex}"})
        sys.exit(0)

    patched_source = req["patched_source"]
    test_source = req["test_source"]
    module_name = req.get("module_name", "patched_under_test")

    # Compile patched source.
    try:
        code = compile(patched_source, f"<{module_name}>", "exec")
    except SyntaxError as ex:
        _emit({"ok": False, "kind": "syntax",
               "detail": f"{type(ex).__name__}: {ex}"})
        sys.exit(0)
    mod_globals = {"__name__": module_name, "__doc__": None,
                   "__builtins__": __builtins__}
    try:
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            exec(code, mod_globals)
    except Exception as ex:
        _emit({"ok": False, "kind": "import",
               "detail": f"{type(ex).__name__}: {ex}"})
        sys.exit(0)

    # Compile + exec test source.
    try:
        test_code = compile(test_source, "<patched_test>", "exec")
        test_globals = {"__name__": "<patched_test>", "__doc__": None,
                        "__builtins__": __builtins__}
        exec(test_code, test_globals)
    except SyntaxError as ex:
        _emit({"ok": False, "kind": "syntax",
               "detail": f"test syntax: {ex}"})
        sys.exit(0)
    test_fn = test_globals.get("test")
    if not callable(test_fn):
        _emit({"ok": False, "kind": "test_exception",
               "detail": "test source did not define test(module)"})
        sys.exit(0)
    class _Mod: pass
    mod_obj = _Mod()
    for k, v in mod_globals.items():
        if not k.startswith("__"):
            setattr(mod_obj, k, v)
    try:
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            test_fn(mod_obj)
    except AssertionError as ex:
        _emit({"ok": False, "kind": "test_assert",
               "detail": str(ex)[:300]})
        sys.exit(0)
    except Exception as ex:
        _emit({"ok": False, "kind": "test_exception",
               "detail": f"{type(ex).__name__}: {ex}"})
        sys.exit(0)
    _emit({"ok": True, "kind": "", "detail": ""})
''')


@dataclass
class SubprocessSandbox:
    """Run patched + test source in a fresh ``python`` subprocess.

    Each ``run`` call:

      * writes a temp directory containing the runner script;
      * spawns ``python <runner>`` with the patch payload on
        stdin;
      * enforces ``timeout_s`` via ``subprocess.run(timeout=...)``;
      * captures stdout / stderr bytes;
      * parses the runner's single JSON line back into a
        ``WorkspaceResult``.

    The subprocess is started with ``stdin=PIPE``, ``stdout=PIPE``,
    ``stderr=PIPE``, no inherited file descriptors beyond those
    three, and ``cwd=<tempdir>``. On Unix, ``preexec_fn=os.setsid``
    starts a new process group so a ``timeout`` triggers
    ``Popen.kill()`` against the whole group rather than just the
    leader.
    """

    python_executable: str = field(default_factory=lambda: sys.executable)
    pass_environ: bool = False  # if False, child gets a minimal env

    def name(self) -> str:
        return "subprocess"

    def is_available(self) -> bool:
        return os.path.exists(self.python_executable)

    def run(self,
            *,
            buggy_source: str,
            patch: tuple[tuple[str, str], ...],
            test_source: str,
            module_name: str,
            timeout_s: float = 30.0,
            apply_mode: str = APPLY_MODE_STRICT,
            ) -> WorkspaceResult:
        new_source, applied, reason = apply_patch(
            buggy_source, patch, mode=apply_mode)
        if not applied:
            return WorkspaceResult(
                patch_applied=False, syntax_ok=False,
                test_passed=False, error_kind="patch_no_match",
                error_detail=reason)
        with tempfile.TemporaryDirectory(prefix="ctxzero_swe_") as tmp:
            runner_path = os.path.join(tmp, "_runner.py")
            with open(runner_path, "w", encoding="utf-8") as fh:
                fh.write(_SUBPROCESS_RUNNER)
            payload = json.dumps({
                "patched_source": new_source,
                "test_source": test_source,
                "module_name": module_name,
            }).encode("utf-8")
            env = (os.environ.copy() if self.pass_environ
                    else {"PATH": os.environ.get("PATH", ""),
                          "PYTHONHASHSEED": "0",
                          "PYTHONIOENCODING": "utf-8",
                          "LANG": "C.UTF-8",
                          "PYTHONDONTWRITEBYTECODE": "1"})
            t0 = time.time()
            try:
                proc = subprocess.run(
                    [self.python_executable, "-S", "-B", runner_path],
                    input=payload, capture_output=True,
                    timeout=timeout_s, cwd=tmp, env=env, check=False)
            except subprocess.TimeoutExpired as ex:
                return WorkspaceResult(
                    patch_applied=True, syntax_ok=True,
                    test_passed=False, error_kind="timeout",
                    error_detail=(
                        f"subprocess exceeded timeout_s={timeout_s} "
                        f"(wall={time.time() - t0:.2f}s); "
                        f"stdout_chars={len(ex.stdout or b'')} "
                        f"stderr_chars={len(ex.stderr or b'')}"))
            except (OSError, ValueError) as ex:
                return WorkspaceResult(
                    patch_applied=True, syntax_ok=False,
                    test_passed=False, error_kind="sandbox_error",
                    error_detail=f"spawn failed: {type(ex).__name__}: {ex}")
            return _parse_runner_payload(proc, new_source)


def _parse_runner_payload(proc: subprocess.CompletedProcess,
                            patched_source: str) -> WorkspaceResult:
    """Convert the subprocess runner's stdout into a WorkspaceResult.

    Handles three failure shapes: (a) the runner emitted a clean
    JSON outcome (the common path); (b) the runner crashed before
    emitting (returncode != 0, stdout empty); (c) the runner
    emitted partial / malformed output (capture as
    ``sandbox_error`` so the failure is attributable to the
    boundary, not to the patch).
    """
    stdout = (proc.stdout or b"").decode("utf-8", errors="replace").strip()
    stderr = (proc.stderr or b"").decode("utf-8", errors="replace")
    # Take the last non-empty stdout line — the runner emits
    # exactly one JSON line on a clean run.
    last = ""
    for line in stdout.splitlines():
        if line.strip():
            last = line.strip()
    if not last:
        return WorkspaceResult(
            patch_applied=True, syntax_ok=bool(patched_source),
            test_passed=False, error_kind="sandbox_error",
            error_detail=(
                f"runner produced no JSON output; "
                f"returncode={proc.returncode}; "
                f"stderr_head={stderr[:200]!r}"))
    try:
        outcome = json.loads(last)
    except json.JSONDecodeError as ex:
        return WorkspaceResult(
            patch_applied=True, syntax_ok=True,
            test_passed=False, error_kind="sandbox_error",
            error_detail=(
                f"runner JSON parse failed: {ex}; "
                f"last_line={last[:200]!r}"))
    if not isinstance(outcome, dict):
        return WorkspaceResult(
            patch_applied=True, syntax_ok=True,
            test_passed=False, error_kind="sandbox_error",
            error_detail=f"runner outcome not a dict: {type(outcome).__name__}")
    ok = bool(outcome.get("ok", False))
    kind = str(outcome.get("kind", ""))
    detail = str(outcome.get("detail", ""))[:300]
    if ok:
        return WorkspaceResult(
            patch_applied=True, syntax_ok=True,
            test_passed=True, error_kind="", error_detail="")
    syntax_ok = kind not in ("syntax",)
    return WorkspaceResult(
        patch_applied=True, syntax_ok=syntax_ok,
        test_passed=False, error_kind=kind or "sandbox_error",
        error_detail=detail)


# =============================================================================
# Docker sandbox (optional)
# =============================================================================


@dataclass
class DockerSandbox:
    """Run the patch+test cycle inside a short-lived Docker container.

    Each ``run`` materialises a tempdir on the host containing the
    runner script and the JSON payload, then invokes::

        docker run --rm \\
            --network=none \\
            --read-only \\
            --tmpfs /work:rw,size=64m,mode=1777 \\
            -v <host_tmp>:/work/in:ro \\
            <image> python /work/in/_runner.py < /work/in/_payload.json

    The container has no network, no writable rootfs, no
    inherited environment beyond what the image specifies, and a
    wall-clock kill via ``--stop-timeout``. The runner script is
    the same one ``SubprocessSandbox`` uses, so the parsed
    ``WorkspaceResult`` shape is identical.

    Docker is *optional*. ``is_available`` returns False if the
    daemon is unreachable; the driver falls back to
    ``SubprocessSandbox``.
    """

    image: str = "python:3.11-slim"
    docker_bin: str = "docker"

    def name(self) -> str:
        return "docker"

    def is_available(self) -> bool:
        bin_path = shutil.which(self.docker_bin)
        if not bin_path:
            return False
        try:
            r = subprocess.run(
                [bin_path, "info", "--format", "{{.ServerVersion}}"],
                capture_output=True, timeout=4.0, check=False)
            return r.returncode == 0
        except Exception:
            return False

    def run(self,
            *,
            buggy_source: str,
            patch: tuple[tuple[str, str], ...],
            test_source: str,
            module_name: str,
            timeout_s: float = 60.0,
            apply_mode: str = APPLY_MODE_STRICT,
            ) -> WorkspaceResult:
        new_source, applied, reason = apply_patch(
            buggy_source, patch, mode=apply_mode)
        if not applied:
            return WorkspaceResult(
                patch_applied=False, syntax_ok=False,
                test_passed=False, error_kind="patch_no_match",
                error_detail=reason)
        if not self.is_available():
            return WorkspaceResult(
                patch_applied=True, syntax_ok=False,
                test_passed=False, error_kind="sandbox_error",
                error_detail="docker not available; use a different backend")
        with tempfile.TemporaryDirectory(prefix="ctxzero_dock_") as tmp:
            runner_path = os.path.join(tmp, "_runner.py")
            payload_path = os.path.join(tmp, "_payload.json")
            with open(runner_path, "w", encoding="utf-8") as fh:
                fh.write(_SUBPROCESS_RUNNER)
            with open(payload_path, "w", encoding="utf-8") as fh:
                json.dump({
                    "patched_source": new_source,
                    "test_source": test_source,
                    "module_name": module_name,
                }, fh)
            cmd = [
                self.docker_bin, "run", "--rm",
                "--network=none", "--read-only",
                "--tmpfs", "/work:rw,size=64m,mode=1777",
                "-v", f"{tmp}:/work/in:ro",
                "-w", "/work",
                "--stop-timeout", str(int(timeout_s) + 2),
                self.image,
                "sh", "-c",
                "python /work/in/_runner.py < /work/in/_payload.json",
            ]
            t0 = time.time()
            try:
                proc = subprocess.run(
                    cmd, capture_output=True,
                    timeout=timeout_s + 5.0, check=False)
            except subprocess.TimeoutExpired as ex:
                return WorkspaceResult(
                    patch_applied=True, syntax_ok=True,
                    test_passed=False, error_kind="timeout",
                    error_detail=(
                        f"docker run exceeded timeout_s={timeout_s} "
                        f"(wall={time.time() - t0:.2f}s); "
                        f"stderr_head={(ex.stderr or b'')[:200]!r}"))
            except FileNotFoundError as ex:
                return WorkspaceResult(
                    patch_applied=True, syntax_ok=False,
                    test_passed=False, error_kind="sandbox_error",
                    error_detail=f"docker binary not found: {ex}")
            return _parse_runner_payload(proc, new_source)


# =============================================================================
# Sandbox factory
# =============================================================================


def select_sandbox(name: str = "auto",
                    *,
                    docker_image: str = "python:3.11-slim",
                    ) -> Sandbox:
    """Return the requested sandbox backend.

    ``name`` ∈ {``"in_process"``, ``"subprocess"``, ``"docker"``,
    ``"auto"``}. ``"auto"`` prefers Docker → subprocess →
    in_process based on availability. The driver records the
    selected backend's ``name()`` in the result artifact so the
    measurement is fully attributable.
    """
    if name == "in_process":
        return InProcessSandbox()
    if name == "subprocess":
        return SubprocessSandbox()
    if name == "docker":
        return DockerSandbox(image=docker_image)
    if name == "auto":
        d = DockerSandbox(image=docker_image)
        if d.is_available():
            return d
        s = SubprocessSandbox()
        if s.is_available():
            return s
        return InProcessSandbox()
    raise ValueError(f"unknown sandbox name {name!r}")


# =============================================================================
# Substrate-loop integration (Phase 40 sandbox-aware runner)
# =============================================================================


def run_swe_loop_sandboxed(*,
                            bank,
                            repo_files: dict[str, str],
                            generator,
                            sandbox: Sandbox,
                            strategies=None,
                            timeout_s: float = 30.0,
                            apply_mode: str = APPLY_MODE_STRICT,
                            ):
    """Phase-40 alternative to ``run_swe_loop`` that routes the
    workspace test through ``sandbox`` instead of the in-process
    runner.

    Identical to ``swe_bench_bridge.run_swe_loop`` except that:

      * the patch+test step is replaced by ``sandbox.run(...)``;
      * each ``SWEMeasurement`` records ``sandbox.name()`` in the
        ``error_detail`` (when there is a failure) so the
        artifact tells the reader which boundary was crossed.

    Kept in this module rather than reaching back into
    ``swe_bench_bridge`` so the bridge remains untouched if a
    caller wants the Phase-39 in-process semantics exactly.
    """
    from .swe_bench_bridge import (
        ALL_SWE_STRATEGIES, ALL_SWE_ROLES,
        ROLE_PATCH_GENERATOR, ROLE_TEST_RUNNER,
        STRATEGY_NAIVE, STRATEGY_ROUTING, STRATEGY_SUBSTRATE,
        CLAIM_PATCH_PROPOSED, CLAIM_TEST_RESULT,
        DeliveryAccount, HandoffLog, HandoffRouter, RoleInbox,
        SWEMeasurement, SWEReport, ProposedPatch,
        _build_patch_gen_context, _build_patch_gen_prompt_for_strategy,
        _emit_substrate_handoffs, build_swe_role_subscriptions,
        _EVENT_TYPE_FILE_HEADER, _EVENT_TYPE_FUNCTION_BODY,
        _EVENT_TYPE_ISSUE,
    )
    if strategies is None:
        strategies = ALL_SWE_STRATEGIES
    measurements = []
    for task in bank:
        buggy_source = repo_files[task.buggy_file_relpath]
        all_events = list(task.hidden_event_log)
        issue_events = [
            ev for ev in all_events if ev[0] == _EVENT_TYPE_ISSUE]
        code_events = [
            ev for ev in all_events
            if ev[0] in (_EVENT_TYPE_FILE_HEADER, _EVENT_TYPE_FUNCTION_BODY)]
        for strat in strategies:
            t0 = time.time()
            subs = build_swe_role_subscriptions()
            log = HandoffLog()
            account = DeliveryAccount()
            router = HandoffRouter(subs=subs, log=log, account=account)
            for r in ALL_SWE_ROLES:
                router.register_inbox(RoleInbox(role=r, capacity=64))
            n_handoffs = 0
            if strat == STRATEGY_SUBSTRATE:
                n_handoffs = _emit_substrate_handoffs(
                    task=task, router=router,
                    issue_events=issue_events,
                    code_events=code_events)
            ctx, delivered = _build_patch_gen_context(
                strategy=strat, task=task,
                buggy_source=buggy_source,
                issue_events=issue_events,
                code_events=code_events,
                all_events=all_events)
            prompt = _build_patch_gen_prompt_for_strategy(
                strategy=strat, task=task,
                buggy_source=buggy_source, ctx=ctx,
                delivered_events=delivered)
            issue_summary = ctx.get("issue_summary", task.problem_statement)
            try:
                proposed = generator(task, ctx, buggy_source, issue_summary)
            except Exception as ex:
                proposed = ProposedPatch(
                    patch=(), rationale=f"gen_error:{type(ex).__name__}")
            wr = sandbox.run(
                buggy_source=buggy_source, patch=proposed.patch,
                test_source=task.test_source,
                module_name=f"patched_{task.instance_id}",
                timeout_s=timeout_s, apply_mode=apply_mode)
            if wr.patch_applied:
                router.emit(
                    source_role=ROLE_PATCH_GENERATOR,
                    source_agent_id=0,
                    claim_kind=CLAIM_PATCH_PROPOSED,
                    payload=f"{task.instance_id}:applied",
                    source_event_ids=(), round=2)
                n_handoffs += 1
                verdict = "pass" if wr.test_passed else f"fail:{wr.error_kind}"
                router.emit(
                    source_role=ROLE_TEST_RUNNER, source_agent_id=0,
                    claim_kind=CLAIM_TEST_RESULT, payload=verdict,
                    source_event_ids=(), round=3)
                n_handoffs += 1
            wall = time.time() - t0
            # Attribute the boundary on failure detail.
            detail = wr.error_detail
            if not wr.test_passed and detail:
                detail = f"[{sandbox.name()}] {detail}"
            measurements.append(SWEMeasurement(
                instance_id=task.instance_id, repo=task.repo,
                strategy=strat, test_passed=wr.test_passed,
                patch_applied=wr.patch_applied,
                error_kind=wr.error_kind,
                n_events_to_patch_gen=len(delivered),
                n_chars_patch_gen_prompt=len(prompt),
                n_handoffs=n_handoffs,
                n_events_total=len(all_events),
                log_length=router.log_length(),
                chain_ok=router.verify(),
                wall_seconds=wall))
            # Stash the sandbox-attributed detail on the in-memory
            # measurement; SWEMeasurement.as_dict caps it at 300.
            measurements[-1].error_kind = wr.error_kind
    return SWEReport(
        n_tasks=len(bank),
        measurements=measurements,
        config={
            "strategies": list(strategies),
            "n_tasks": len(bank),
            "sandbox": sandbox.name(),
            "timeout_s": timeout_s,
            "apply_mode": apply_mode,
        })


__all__ = [
    "Sandbox", "InProcessSandbox", "SubprocessSandbox", "DockerSandbox",
    "select_sandbox", "run_swe_loop_sandboxed",
]
