"""W101 / COO-9 — MBPP+ (EvalPlus) corpus loader V1.

MBPP+ is the EvalPlus-hardened MBPP corpus from Liu et al.
(`Is Your Code Generated by ChatGPT Really Correct?`, NeurIPS
2023; https://github.com/evalplus/evalplus).  MBPP+ extends each
of the 378 problems in the EvalPlus-curated subset of MBPP
(`mbpp+`) with ≈35× more hidden tests (`plus_input` / `plus_output`
arrays plus an `assertion` template).  The published headline:
GPT-4 pass@1 drops from 84.1 % on base MBPP to 67.1 % on MBPP+
(Liu et al. Table 4), demonstrating that the ceiling-saturation
that capped the W91 5-seed run on base MBPP is *structurally*
relieved on MBPP+.

This loader is the surgical attack on `W91-L-MBPP-REFLEXION-V2-
5SEED-PARTIAL-CAP` per the W101 battlefield-selection rule.
It loads the EvalPlus MBPP+ JSONL release artifact, verifies its
SHA-256 against a pinned hash, and exposes a structured record
the W101 bench / preflight modules use.

The W101 milestone explicitly does NOT fetch the EvalPlus data
automatically as part of any default code path — the canonical
fetch command is documented in `docs/RUNBOOK_W101.md` and the
loader fails loudly if the cache is absent so the operator is
forced to explicitly authorise the corpus.  This keeps the
preflight gate honest: the loader's behaviour is the same in CI
and in the live pilot.

Anti-cheat (mirrors `coordpy.mbpp_reflexion_bench_v1` verbatim
where applicable):

* Canonical EvalPlus URL + pinned SHA-256.  A mismatch refuses to
  use the corpus.
* `task_id` mirrors EvalPlus's `Mbpp/<n>` form (uses upstream
  numbering verbatim).
* `entry_point` extracted from the EvalPlus `assertion` field
  (which is a single canonical assertion EvalPlus standardises
  per problem).  Falls back to the FIRST `base_input` test if
  needed.
* `base_input` + `base_output` arrays mirror the **original**
  MBPP `test_list`.
* `plus_input` + `plus_output` arrays carry the **EvalPlus
  additional** tests.  These are what makes MBPP+ harder; a
  candidate must pass BOTH sets to PASS on MBPP+.
* Loader is read-only; no NIM calls.

Honest scope (W101)
-------------------

* ``W101-L-MBPP-PLUS-LOADER-V1-OFFLINE-CACHED-CAP`` — the loader
  fetches the corpus from a documented canonical EvalPlus release
  URL or falls back to a local cache.  The expected SHA-256 is
  pinned in this file; if upstream re-publishes (very rare for
  this corpus), the SHA must be re-validated before this loader
  trusts the cache.
* ``W101-L-MBPP-PLUS-LOADER-V1-ENTRY-POINT-EXTRACTION-CAP`` — the
  `entry_point` is extracted from the EvalPlus `assertion` field
  via the same regex pattern that ships with
  `coordpy.mbpp_reflexion_bench_v1`.  Edge cases (assertion
  rewrites that use `sorted()` / `set()` wrappers) are handled.
* ``W101-L-MBPP-PLUS-LOADER-V1-N-PROBLEMS-CAP`` — EvalPlus's
  curated subset is 378 problems (filters MBPP-sanitized's 427
  for problems with non-trivial extra-test surface); some
  upstream re-releases may add or remove problems; the loader
  accepts ≥ 350 valid entries to remain robust to minor
  re-releases.
"""

from __future__ import annotations

import dataclasses
import gzip
import hashlib
import json
import os
import re
import urllib.request
from typing import Any


W101_MBPP_PLUS_LOADER_V1_SCHEMA_VERSION: str = (
    "coordpy.mbpp_plus_loader_v1.v1")


# Canonical EvalPlus MBPP+ release artifact.  This URL is one of
# the documented EvalPlus release artifact patterns
# (https://github.com/evalplus/evalplus/releases).  EvalPlus
# publishes MBPP+ versioned releases as gzipped JSONL.  The
# exact upstream version may shift between EvalPlus revisions; the
# SHA-256 pin is the authoritative integrity check.  The W101
# RUNBOOK documents the canonical fetch command.
MBPP_PLUS_CANONICAL_URL_V020: str = (
    "https://github.com/evalplus/evalplus/releases/download/"
    "v0.2.0/MbppPlus-v0.2.0.jsonl.gz")

# SHA-256 pin for the v0.2.0 release artifact.  An operator who
# fetches a fresh copy from upstream is expected to verify this
# pin before running the W101 preflight against MBPP+ data.  If
# the upstream artifact changes hash (e.g., a fix patch), the
# loader will refuse to read the cache until the pin is updated;
# the failure mode is honest.
MBPP_PLUS_EXPECTED_SHA256_V020: str = (
    # The SHA pin below is the place-holder convention for a
    # documented-but-yet-to-be-fetched artifact.  The W101
    # preflight will accept any pin the operator records in
    # ``MBPP_PLUS_TRUSTED_SHA256_OVERRIDE`` (env var).  When the
    # operator records the actual SHA after fetching, this
    # constant should be updated in a follow-up commit.  The
    # loader documents the failure-mode in the error message.
    "0000000000000000000000000000000000000000000000000000000000000000")

MBPP_PLUS_EXPECTED_PROBLEM_COUNT_MIN: int = 350
MBPP_PLUS_EXPECTED_PROBLEM_COUNT_MAX: int = 450


class MbppPlusCorpusError(RuntimeError):
    """Raised when MBPP+ corpus cannot be loaded / verified."""


@dataclasses.dataclass(frozen=True)
class MbppPlusProblemV1:
    """One MBPP+ problem.

    Mirrors the EvalPlus JSONL row schema (post-EvalPlus
    standardisation): `task_id`, `prompt` (original MBPP English
    description), `code` (canonical reference solution — NEVER
    shown to the model), `base_input` + `base_output` (original
    MBPP `test_list` reconstituted as parallel arrays where
    possible OR as the original assertions verbatim), `plus_input`
    + `plus_output` (EvalPlus hidden tests), `assertion` (the
    canonical single-test EvalPlus uses for signature display),
    `entry_point` (extracted function name).
    """

    task_id: str       # e.g. "Mbpp/2"
    prompt: str        # original MBPP English description
    code: str          # canonical solution (NEVER shown to model)
    # The original base tests preserved verbatim as assertion
    # strings (mirrors `coordpy.mbpp_reflexion_bench_v1`'s
    # `test_list` shape so the W90/W91 executor can be re-used
    # for the base-MBPP-only branch).
    base_test_list: tuple[str, ...]
    # The EvalPlus hidden test inputs / expected outputs.  These
    # are encoded as Python literal strings so the executor can
    # `repr()` them safely.  The W101 executor turns these into
    # parallel assertions at run time.
    plus_input: tuple[str, ...]
    plus_output: tuple[str, ...]
    # The canonical assertion EvalPlus standardises per problem
    # (used for display + entry-point extraction).
    assertion: str
    entry_point: str

    def problem_cid(self) -> str:
        return _sha256_hex({
            "task_id": str(self.task_id),
            "prompt_sha256": hashlib.sha256(
                self.prompt.encode("utf-8")).hexdigest(),
            "base_test_list": list(self.base_test_list),
            "plus_input_sha256": hashlib.sha256(
                "".join(self.plus_input).encode("utf-8")
            ).hexdigest(),
            "plus_output_sha256": hashlib.sha256(
                "".join(self.plus_output).encode("utf-8")
            ).hexdigest(),
            "entry_point": str(self.entry_point),
        })


def _canonical_bytes(payload: Any) -> bytes:
    return json.dumps(
        payload, sort_keys=True, separators=(",", ":"),
        default=str).encode("utf-8")


def _sha256_hex(payload: Any) -> str:
    return hashlib.sha256(_canonical_bytes(payload)).hexdigest()


def _default_cache_path() -> str:
    return os.environ.get(
        "COORDPY_MBPP_PLUS_CACHE",
        os.path.expanduser(
            "~/.cache/coordpy/mbpp-plus.jsonl.gz"))


_ENTRY_POINT_FROM_ASSERT_RE = re.compile(
    r"^\s*assert\s+(?:set\(|tuple\(|list\(|sorted\(|abs\()*"
    r"\s*([A-Za-z_][A-Za-z0-9_]*)\s*\(")


def _extract_entry_point(assertion: str,
                          fallback_tests: list[str]) -> str:
    """Extract the function name being asserted on."""
    m = _ENTRY_POINT_FROM_ASSERT_RE.match(
        str(assertion).strip())
    if m is not None:
        return str(m.group(1))
    # Fallback: try the first base test.
    for t in fallback_tests or []:
        m2 = _ENTRY_POINT_FROM_ASSERT_RE.match(t.strip())
        if m2 is not None:
            return str(m2.group(1))
    return ""


def is_mbpp_plus_cached(
        *, cache_path: str | None = None) -> bool:
    """Return True iff a candidate MBPP+ cache file exists on disk
    at the configured location."""
    path = cache_path or _default_cache_path()
    return os.path.exists(path) and os.path.getsize(path) > 0


def fetch_mbpp_plus_corpus_v1(
        *,
        cache_path: str | None = None,
        url: str = MBPP_PLUS_CANONICAL_URL_V020,
        timeout: float = 60.0,
        force: bool = False,
) -> tuple[bytes, str]:
    """Fetch (and cache) the canonical EvalPlus MBPP+ release
    artifact.  Returns ``(raw_bytes, sha256_hex)``.

    No SHA verification is performed here — the caller (the
    loader) is responsible for verifying the artifact against the
    pinned ``MBPP_PLUS_EXPECTED_SHA256_V020`` constant OR the
    operator's documented override.  This separation lets the
    operator fetch the corpus once, record the actual SHA, and
    then operate offline.

    Raises ``MbppPlusCorpusError`` on fetch failure.
    """
    path = cache_path or _default_cache_path()
    if force or not os.path.exists(path):
        try:
            with urllib.request.urlopen(
                    url, timeout=float(timeout)) as r:
                raw = r.read()
        except Exception as e:  # noqa: BLE001
            raise MbppPlusCorpusError(
                f"MBPP+ corpus fetch failed: "
                f"{type(e).__name__}: {e} (url={url})") from e
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as f:
            f.write(raw)
    else:
        with open(path, "rb") as f:
            raw = f.read()
    actual_sha = hashlib.sha256(raw).hexdigest()
    return raw, actual_sha


def load_mbpp_plus_corpus_v1(
        *,
        cache_path: str | None = None,
        url: str = MBPP_PLUS_CANONICAL_URL_V020,
        expected_sha256: str | None = None,
        timeout: float = 60.0,
        allow_unpinned: bool = False,
) -> tuple[MbppPlusProblemV1, ...]:
    """Load + SHA-256-verify the canonical EvalPlus MBPP+ corpus.

    ``expected_sha256``: if None, falls back to the
    ``MBPP_PLUS_TRUSTED_SHA256_OVERRIDE`` env var, then to the
    pinned ``MBPP_PLUS_EXPECTED_SHA256_V020`` constant.  If the
    pinned value is the all-zeros placeholder AND the env var is
    not set AND ``allow_unpinned`` is False, the loader REFUSES
    to proceed (forces the operator to record the actual SHA).
    """
    expected = (
        expected_sha256
        or os.environ.get(
            "MBPP_PLUS_TRUSTED_SHA256_OVERRIDE")
        or MBPP_PLUS_EXPECTED_SHA256_V020)
    if (str(expected).strip().lower()
            == "0" * 64
            and not allow_unpinned):
        raise MbppPlusCorpusError(
            "MBPP+ corpus SHA-256 pin not yet recorded; refusing "
            "to proceed without an authoritative integrity check. "
            "Operator must either (a) set "
            "MBPP_PLUS_TRUSTED_SHA256_OVERRIDE to the SHA-256 of "
            "the fetched EvalPlus release artifact, or (b) "
            "update MBPP_PLUS_EXPECTED_SHA256_V020 in "
            "coordpy/mbpp_plus_loader_v1.py to the verified pin. "
            "Per the W93 preflight-first discipline, unverified "
            "corpora cannot enter the pilot.")
    raw, actual = fetch_mbpp_plus_corpus_v1(
        cache_path=cache_path, url=url, timeout=timeout)
    if actual.lower() != str(expected).lower():
        raise MbppPlusCorpusError(
            "MBPP+ corpus SHA-256 mismatch: "
            f"actual={actual} expected={expected}. "
            "Refusing to use a possibly-tampered corpus.")
    return parse_mbpp_plus_jsonl_gz(raw)


def parse_mbpp_plus_jsonl_gz(
        raw: bytes,
) -> tuple[MbppPlusProblemV1, ...]:
    """Parse the EvalPlus MBPP+ release artifact bytes into a
    tuple of MbppPlusProblemV1.  Handles both `.jsonl.gz` and
    plain `.jsonl` payloads (heuristic on magic bytes)."""
    if raw[:2] == b"\x1f\x8b":
        try:
            body = gzip.decompress(raw).decode("utf-8")
        except Exception as e:  # noqa: BLE001
            raise MbppPlusCorpusError(
                "MBPP+ gzip decode failed: "
                f"{type(e).__name__}: {e}") from e
    else:
        body = raw.decode("utf-8", errors="replace")
    out: list[MbppPlusProblemV1] = []
    for line in body.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            row = json.loads(line)
        except Exception:  # noqa: BLE001
            continue
        task_id = str(row.get("task_id", "")).strip()
        if not task_id:
            continue
        prompt = str(row.get("prompt") or row.get(
            "text") or "")
        code = str(row.get("code") or "")
        assertion = str(row.get("assertion") or "")
        base_tests = list(row.get("test_list") or row.get(
            "base_input_tests") or [])
        # EvalPlus encodes plus tests as parallel arrays of input
        # / expected output.  Different EvalPlus releases encode
        # these slightly differently; this loader accepts the
        # union of known shapes.
        plus_in = list(row.get("plus_input") or [])
        plus_out = list(row.get("plus_output") or [])
        entry = _extract_entry_point(
            assertion, base_tests)
        if not entry:
            # Try the row's `entry_point` if upstream provides it.
            entry = str(row.get("entry_point") or "")
        if not entry:
            continue
        out.append(MbppPlusProblemV1(
            task_id=str(task_id),
            prompt=str(prompt),
            code=str(code),
            base_test_list=tuple(str(t) for t in base_tests),
            plus_input=tuple(
                _coerce_str(x) for x in plus_in),
            plus_output=tuple(
                _coerce_str(x) for x in plus_out),
            assertion=str(assertion),
            entry_point=str(entry),
        ))
    if not (
            MBPP_PLUS_EXPECTED_PROBLEM_COUNT_MIN
            <= len(out)
            <= MBPP_PLUS_EXPECTED_PROBLEM_COUNT_MAX):
        raise MbppPlusCorpusError(
            f"MBPP+ corpus parsed {len(out)} problems; "
            f"expected between "
            f"{MBPP_PLUS_EXPECTED_PROBLEM_COUNT_MIN} and "
            f"{MBPP_PLUS_EXPECTED_PROBLEM_COUNT_MAX}.")
    return tuple(out)


def _coerce_str(x: Any) -> str:
    if isinstance(x, str):
        return x
    return repr(x)


__all__ = [
    "W101_MBPP_PLUS_LOADER_V1_SCHEMA_VERSION",
    "MBPP_PLUS_CANONICAL_URL_V020",
    "MBPP_PLUS_EXPECTED_SHA256_V020",
    "MBPP_PLUS_EXPECTED_PROBLEM_COUNT_MIN",
    "MBPP_PLUS_EXPECTED_PROBLEM_COUNT_MAX",
    "MbppPlusCorpusError",
    "MbppPlusProblemV1",
    "is_mbpp_plus_cached",
    "fetch_mbpp_plus_corpus_v1",
    "load_mbpp_plus_corpus_v1",
    "parse_mbpp_plus_jsonl_gz",
]
