"""W102 / COO-9 — HumanEval+ (EvalPlus) corpus loader V1.

HumanEval+ is the EvalPlus-hardened HumanEval corpus from Liu et
al. (`Is Your Code Generated by ChatGPT Really Correct?`,
NeurIPS 2023; https://github.com/evalplus/evalplus).  HumanEval+
extends each of the 164 original HumanEval problems with ~80×
more hidden tests; the canonical artifact is published on
Hugging Face as a JSONL file at
``https://huggingface.co/datasets/evalplus/humanevalplus/resolve/main/test.jsonl``
(164 rows, LFS oid
``908377f1daf28dcb36846db73a5662b2e05a9907407c2696c89ad9d3b0b04492``).

The row schema is
``{task_id, prompt, canonical_solution, entry_point, test}``.

* ``task_id``: e.g., `"HumanEval/0"`.
* ``prompt``: function signature + docstring (what the model sees).
* ``canonical_solution``: reference body (NEVER shown to model).
* ``entry_point``: the function name (e.g., `has_close_elements`).
* ``test``: a complete Python program that imports numpy, defines
  helpers, and defines a ``check(candidate)`` function which the
  executor invokes with the candidate's entry-point function.

This is structurally identical to base-HumanEval (which the W86
`humaneval_real_bench_v1` already handles cleanly); the only
differences are (a) the `test` field is bigger (EvalPlus extras)
and (b) the `test` program imports numpy.

W102 HumanEval+ is the **BACKUP** battlefield to W102 MBPP+ V2.
Per the W101 battlefield-selection matrix, MBPP+ ranks LEAD
because EvalPlus drops MBPP A1 farther than HumanEval A1 at 70B
(the W89 retirement already cleared base HumanEval at +5.56 pp;
HumanEval+ residual is comfortable but smaller than MBPP+).

Anti-cheat (mirrors W86 + W102 MBPP+ V2 verbatim):

* Canonical Hugging Face URL + pinned SHA-256 (LFS oid).
* `task_id` mirrors EvalPlus's `HumanEval/<n>` form verbatim.
* `entry_point` extracted from the row's `entry_point` field.
* Loader is read-only; no NIM calls.

Honest scope (W102)
-------------------

* ``W102-L-HUMANEVAL-PLUS-LOADER-V1-NUMPY-DEPENDENCY-CAP`` — the
  HumanEval+ `test` programs import numpy at runtime; the V1
  executor's subprocess inherits the system Python and therefore
  must have numpy installed.  If numpy is missing, every problem
  FAILs loudly (no silent degradation).
* ``W102-L-HUMANEVAL-PLUS-LOADER-V1-JSONL-CAP`` — V1 reads the
  raw JSONL.  HF stores it as a single 164-row JSONL (~11 MB
  uncompressed).
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
import os
import urllib.request
from typing import Any


W102_HUMANEVAL_PLUS_LOADER_V1_SCHEMA_VERSION: str = (
    "coordpy.humaneval_plus_loader_v1.v1")


# Canonical Hugging Face HumanEval+ JSONL (v0.2.1 / v0.3.1 row
# shape).  Confirmed live 2026-05-25 during the W102 operator-
# fetch step.
HUMANEVAL_PLUS_HF_CANONICAL_URL_V021: str = (
    "https://huggingface.co/datasets/evalplus/humanevalplus/"
    "resolve/main/test.jsonl")

# LFS SHA-256 oid as exposed by the Hugging Face dataset tree API
# (`/api/datasets/evalplus/humanevalplus/tree/main`).  This is
# the authoritative integrity pin.
HUMANEVAL_PLUS_HF_EXPECTED_SHA256_V021: str = (
    "908377f1daf28dcb36846db73a5662b2e05a9907407c2696c89ad9d3b0b04492")

HUMANEVAL_PLUS_EXPECTED_PROBLEM_COUNT: int = 164


class HumanEvalPlusCorpusError(RuntimeError):
    """Raised when the HumanEval+ corpus cannot be loaded /
    verified."""


@dataclasses.dataclass(frozen=True)
class HumanEvalPlusProblemV1:
    """One HumanEval+ problem (EvalPlus schema).

    Fields mirror the upstream JSONL row schema verbatim:

    * ``task_id``: e.g., `"HumanEval/0"`.
    * ``prompt``: function signature + docstring (model-visible).
    * ``canonical_solution``: reference body (NEVER shown to model).
    * ``test``: complete Python program defining `check(candidate)`.
    * ``entry_point``: function name (e.g., `has_close_elements`).
    """

    task_id: str
    prompt: str
    canonical_solution: str
    test: str
    entry_point: str

    def prompt_cid(self) -> str:
        return hashlib.sha256(
            self.prompt.encode("utf-8")).hexdigest()

    def problem_cid(self) -> str:
        return _sha256_hex({
            "task_id": str(self.task_id),
            "prompt_sha256": self.prompt_cid(),
            "test_sha256": hashlib.sha256(
                self.test.encode("utf-8")).hexdigest(),
            "entry_point": str(self.entry_point),
        })


def _canonical_bytes(payload: Any) -> bytes:
    return json.dumps(
        payload, sort_keys=True, separators=(",", ":"),
        default=str).encode("utf-8")


def _sha256_hex(payload: Any) -> str:
    return hashlib.sha256(_canonical_bytes(payload)).hexdigest()


def _default_cache_path() -> str:
    return os.environ.get(
        "COORDPY_HUMANEVAL_PLUS_CACHE",
        os.path.expanduser(
            "~/.cache/coordpy/humaneval-plus.jsonl"))


def is_humaneval_plus_cached(
        *, cache_path: str | None = None) -> bool:
    """Return True iff a candidate HumanEval+ cache file exists
    on disk at the configured location."""
    path = cache_path or _default_cache_path()
    return os.path.exists(path) and os.path.getsize(path) > 0


def fetch_humaneval_plus_corpus_v1(
        *,
        cache_path: str | None = None,
        url: str = HUMANEVAL_PLUS_HF_CANONICAL_URL_V021,
        timeout: float = 60.0,
        force: bool = False,
) -> tuple[bytes, str]:
    """Fetch (and cache) the canonical EvalPlus HumanEval+ JSONL.
    Returns ``(raw_bytes, sha256_hex)``.

    No SHA verification is performed here — the caller (the
    loader) is responsible.  Separation lets the operator fetch
    the corpus once, record the actual SHA, and operate offline.

    Raises ``HumanEvalPlusCorpusError`` on fetch failure.
    """
    path = cache_path or _default_cache_path()
    if force or not os.path.exists(path):
        try:
            with urllib.request.urlopen(
                    url, timeout=float(timeout)) as r:
                raw = r.read()
        except Exception as e:  # noqa: BLE001
            raise HumanEvalPlusCorpusError(
                f"HumanEval+ corpus fetch failed: "
                f"{type(e).__name__}: {e} (url={url})") from e
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as f:
            f.write(raw)
    else:
        with open(path, "rb") as f:
            raw = f.read()
    actual_sha = hashlib.sha256(raw).hexdigest()
    return raw, actual_sha


def load_humaneval_plus_corpus_v1(
        *,
        cache_path: str | None = None,
        url: str = HUMANEVAL_PLUS_HF_CANONICAL_URL_V021,
        expected_sha256: str | None = None,
        timeout: float = 60.0,
) -> tuple[HumanEvalPlusProblemV1, ...]:
    """Load + SHA-256-verify the canonical EvalPlus HumanEval+
    corpus.

    ``expected_sha256``: if None, falls back to the
    ``HUMANEVAL_PLUS_TRUSTED_SHA256_OVERRIDE`` env var, then to
    the pinned ``HUMANEVAL_PLUS_HF_EXPECTED_SHA256_V021`` constant
    (the authoritative HF LFS oid).
    """
    expected = (
        expected_sha256
        or os.environ.get(
            "HUMANEVAL_PLUS_TRUSTED_SHA256_OVERRIDE")
        or HUMANEVAL_PLUS_HF_EXPECTED_SHA256_V021)
    raw, actual = fetch_humaneval_plus_corpus_v1(
        cache_path=cache_path, url=url, timeout=timeout)
    if actual.lower() != str(expected).lower():
        raise HumanEvalPlusCorpusError(
            "HumanEval+ corpus SHA-256 mismatch: "
            f"actual={actual} expected={expected}. "
            "Refusing to use a possibly-tampered corpus.")
    return parse_humaneval_plus_jsonl(raw)


def parse_humaneval_plus_jsonl(
        raw: bytes,
) -> tuple[HumanEvalPlusProblemV1, ...]:
    """Parse the EvalPlus HumanEval+ JSONL bytes into a tuple of
    ``HumanEvalPlusProblemV1``."""
    body = raw.decode("utf-8", errors="replace")
    out: list[HumanEvalPlusProblemV1] = []
    for line in body.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            row = json.loads(line)
        except Exception:  # noqa: BLE001
            continue
        task_id = str(row.get("task_id") or "").strip()
        if not task_id:
            continue
        prompt = str(row.get("prompt") or "")
        canonical_solution = str(
            row.get("canonical_solution") or "")
        test = str(row.get("test") or "")
        entry_point = str(
            row.get("entry_point") or "").strip()
        if not entry_point:
            continue
        if not test.strip():
            continue
        out.append(HumanEvalPlusProblemV1(
            task_id=str(task_id),
            prompt=str(prompt),
            canonical_solution=str(canonical_solution),
            test=str(test),
            entry_point=str(entry_point),
        ))
    if len(out) != HUMANEVAL_PLUS_EXPECTED_PROBLEM_COUNT:
        raise HumanEvalPlusCorpusError(
            f"HumanEval+ corpus parsed {len(out)} problems; "
            f"expected exactly "
            f"{HUMANEVAL_PLUS_EXPECTED_PROBLEM_COUNT}.")
    return tuple(out)


__all__ = [
    "W102_HUMANEVAL_PLUS_LOADER_V1_SCHEMA_VERSION",
    "HUMANEVAL_PLUS_HF_CANONICAL_URL_V021",
    "HUMANEVAL_PLUS_HF_EXPECTED_SHA256_V021",
    "HUMANEVAL_PLUS_EXPECTED_PROBLEM_COUNT",
    "HumanEvalPlusCorpusError",
    "HumanEvalPlusProblemV1",
    "is_humaneval_plus_cached",
    "fetch_humaneval_plus_corpus_v1",
    "load_humaneval_plus_corpus_v1",
    "parse_humaneval_plus_jsonl",
]
